### PR TITLE
 Use op-related macros instead of accessing op->op_sibling

### PR DESCRIPTION
**Pull request by autarch**
The op_sibling field is no longer available when Perl is compiled with -DPERL_OP_PARENT. This flag became the default in 5.25.1. There are a number of macros to replace direct access of this struct field.

### CODE REVIEW

**Comment by autarch** [comment]
It'd be great if we could get @rafl to review this.

**Review by rafl — APPROVED** [review]
Looks good - thanks!

Did the op code structures change so we now have to use these macros for compatibility?

**Comment by autarch** [comment]
@rafl - the change actually happened in https://perl5.git.perl.org/perl.git/commit/29e61fd971cd4373e17cf1dd6e954ddea5171299

That `-DPERL_OP_PARENT` flag became the default in 5.25.1, breaking List::Gather. Some of the new macros were added in https://perl5.git.perl.org/perl.git/commit/5e24af7dc1ab912b3a8f822d37f232e8ef19779d. I think they replaced existing macros that you probably should have been using, like `OpSIBLING_set` (which is now gone).

**Comment by karenetheridge** [comment]
I took a look at this when the original opsibling changes went through in blead (5.25.1), but this was one of the distributions I was unable to migrate easily, as some of its use of the op tree is a bit tricky -- I think in a few places we should be using OpMAYBESIB_set(...) instead of making a direct macro translation.

@rafl see the notes in pod/perl5251delta.pod and pod/perl5220delta.pod.

(I'm happy to ship when we're satisfied that the changes are correct.)

**Comment by autarch** [comment]
Yeah, if some of the places where I changed it to call `OpMORESIB_set` might be passing `NULL` as the op, they should be changed to `OpMAYBESIB_set` instead. I suspect we could just change them all anyway and it'd work, maybe slightly less efficiently.

**Comment by karenetheridge** [comment]
I shipped a patch from Dave Mitchell via https://rt.cpan.org/Ticket/Display.html?id=116694, but I'm going to leave this PR open pending possible clarification of a "better" way to handle these code changes.

**Comment by karenetheridge** [comment]
Dave clarified that op_sibling_splice is nicer. closing!

**Pull request closed without merging**
